-- generated by BDS portal
DROP TABLE IF EXISTS patient CASCADE;
DROP TABLE IF EXISTS doctor CASCADE;
DROP TABLE IF EXISTS doctor_patient CASCADE;
DROP TABLE IF EXISTS patients CASCADE;

CREATE TABLE appointment (
    id_appointment SERIAL NOT NULL,
    patient_id INTEGER NOT NULL,
    doctor_id INTEGER NOT NULL,
    "from" TIMESTAMP NOT NULL,
    "to" TIMESTAMP NOT NULL
);
ALTER TABLE appointment ADD CONSTRAINT pk_appointment PRIMARY KEY (id_appointment);

CREATE TABLE doctor (
    id_doctor SERIAL NOT NULL,
    name VARCHAR(256) NOT NULL,
    email_address VARCHAR(256) NOT NULL,
    phone_number VARCHAR(256) NOT NULL
);
ALTER TABLE doctor ADD CONSTRAINT pk_doctor PRIMARY KEY (id_doctor);

CREATE TABLE patient (
    id_patient SERIAL NOT NULL,
    name VARCHAR(256) NOT NULL,
    birthdate DATE NOT NULL,
    email_address VARCHAR(256),
    phone_number VARCHAR(256)
);
ALTER TABLE patient ADD CONSTRAINT pk_patient PRIMARY KEY (id_patient);

CREATE TABLE doctor_patient (
    doctor_id INTEGER NOT NULL,
    patient_id INTEGER NOT NULL
);
ALTER TABLE doctor_patient ADD CONSTRAINT pk_doctor_patient PRIMARY KEY (doctor_id, patient_id);

ALTER TABLE appointment ADD CONSTRAINT fk_appointment_patient FOREIGN KEY (patient_id) REFERENCES patient (id_patient) ON DELETE CASCADE;
ALTER TABLE appointment ADD CONSTRAINT fk_appointment_doctor FOREIGN KEY (doctor_id) REFERENCES doctor (id_doctor) ON DELETE CASCADE;

ALTER TABLE doctor_patient ADD CONSTRAINT fk_doctor_patient_doctor FOREIGN KEY (doctor_id) REFERENCES doctor (id_doctor) ON DELETE CASCADE;
ALTER TABLE doctor_patient ADD CONSTRAINT fk_doctor_patient_patient FOREIGN KEY (patient_id) REFERENCES patient (id_patient) ON DELETE CASCADE;
